### ISSUE TITLE
December's Meetup

### ISSUE THREAD

**Issue by jhoguet** [burlingtonjs/burlingtonjs#1]
- [x] Lock in Speaker (Kyle on Meteo)
- [x] Lock in date with speaker (Dec 2)
- [x] Lock in date with Venue
- [x] Tweet it / create meetup
- [x] see if speaker will sponsor, no
- [x] Order Pizza (no pizza this time - no sponsor)
- [x] Get reimbursed if necessary

**Comment by mattparrilla** [comment]
Great, I prefer this to doing this in Google Drive.

**Comment by mattparrilla** [comment]
I am unable to check any of these items, but we're confirmed with MSL

**Comment by jhoguet** [comment]
I added you as a contributor... maybe you now have access...

**Comment by donnie-coleman** [comment]
I'm pretty sure that the state isn't going to sponsor, this time...

**Comment by mattparrilla** [comment]
I can, in fact, check the box now!

@jhoguet Analytics is starting to ask about these expenses. It was Luke who gave the initial OK for this, correct? Any chance you think we could redirect this stuff to recruiting or something? Would I have to talk to Luke about that?

**Comment by jhoguet** [comment]
I emailed luke re - expensing. 

I also marked the meetup created (Donnie is all over it)

**Comment by mattparrilla** [comment]
Just confirmed with Phoebe we're all set for tomorrow!

I'm going to announce in the meetup that there will be no pizza

**Comment by jhoguet** [comment]
@mattparrilla were you able to get reimbursed?

**Comment by mattparrilla** [comment]
@jhoguet it was approved; I get reimbursed tomorrow. Will close it out now.
