### ISSUE TITLE
August Meetup

### ISSUE THREAD

**Issue by jhoguet** [burlingtonjs/burlingtonjs#12]
- [x] Lock in Speaker 
- [x] Lock in date with speaker 
- [x] Lock in date with Venue
- [x] create meetup
- [x] market meetup (eg twitter) 
- [x] see if speaker will sponsor
- [x] Order Pizza (see [doc](https://docs.google.com/document/d/1Qpfft0cuoc03AJjTbfg3PcnlXm28YDyPhRwE8nBonyo/edit?usp=sharing) for process)
- [x] Arrange pick up of pizza

**Comment by jhoguet** [comment]
PS @mattparrilla the issue template worked like a charm 👍

**Comment by mattparrilla** [comment]
@jhoguet can a brother get a _call-for-JS-speakers-for-August-meetup_ tomorrow?

**Comment by jhoguet** [comment]
you'll probably need to remind me - but of course
