### ISSUE TITLE
October Meetup

### ISSUE THREAD

**Issue by mattparrilla** [burlingtonjs/burlingtonjs#14]
- [x] Lock in Speaker 
- [x] Lock in date with speaker 
- [x] Lock in date with [Venue](https://docs.google.com/document/d/1Tt_g3aa0Wn6vGD7tc7jXxhZDIbtMKzSw2o25NlC-ZXI/edit)
- [x] create meetup
- [x] market meetup (eg twitter) 
- [ ] see if speaker will sponsor
- [x] Order Pizza (see [doc](https://docs.google.com/document/d/1Qpfft0cuoc03AJjTbfg3PcnlXm28YDyPhRwE8nBonyo/edit?usp=sharing) for process)
- [x] Arrange pick up of pizza

**Comment by jhoguet** [comment]
@mattparrilla @donnietron can you guys take me out of rotation for a few months, especially someone else take October. 

I have my surgery in early Sep and will be on a liquid diet for a few months. I think I am going to lay low and try to under commit until the new year. 

If that puts you guys in a tough spot let me know and I can try and trade a month and make it work.

**Comment by mattparrilla** [comment]
@jhoguet we got ya. Might be good for the three of us to have a meeting soonish, your participation wouldn't be necessary, but might be good before a leave of absence.

**Comment by mattparrilla** [comment]
Considering ramp up or maybe build environment focused talk.

I'll be out of country and offline next week, so I won't be able to get this going until I return on September 26.

**Comment by jhoguet** [comment]
Consider giving a shout out to LocalVore who is hiring...  they have sponsored us in the past. 

> we are looking for Front End Devs with experience with PHP / MySQL, Laravel, Backbone.js, Cordova, HTML, CSS, Git, GitHub AND passion for Localvore’s mission
