### ISSUE TITLE
Find Additional Coordinator!

### ISSUE THREAD

**Issue by mattparrilla** [burlingtonjs/burlingtonjs#17]
It's getting more challenging to find speakers and our monthly meetings seem to come up faster and faster! I'd love to find another coordinator to help spread the responsibilities.

**Comment by jhoguet** [comment]
I can so relate - that was until I found you guys to help

I am focused on Burlington Code right now (and healing), but if you can't find someone, let me know and of course I will help.

I find myself thinking of Burlington JS and feeling bad... I try to remind myself I am still contributing by providing the space and funding for it (I know you remember when we also had to do that).

Keep up the great work!

**Comment by mattparrilla** [comment]
Definitely do not feel bad @jhoguet! Burlington Code makes this all much easier (thanks for that!) and basically reduces the responsibilities of coordinator to:
- find speaker
- get the word out
- order pizza
- show up

We'll find someone in the community (and hopefully, outside of Dealer.com) to get on board.

However, when you're fully back in action, we'd love to line you up for another talk :-)
