### ISSUE TITLE
Content for Burlingtoncode.org

### ISSUE THREAD

**Issue by jhoguet** [burlingtonjs/burlingtonjs#20]
Burlingtoncode.org is almost done - which is great news as it should drive sponsors to get us more money to keep burlingtoncode.org going. 

It may also prove to be a place for community members to discover burlingtonjs...

if you can provide me a better write up than the canned one Nick quickly threw together https://burlingtoncode.org/meetups/burlington-js/, I can get it updated for you. I can also get one of you admin access so you can just maintain it yourself and add to it as needed.

**Comment by jhoguet** [comment]
FYI @donnietron @mattparrilla

**Comment by mattparrilla** [comment]
On it this week.

**Comment by mattparrilla** [comment]
@jhoguet 

We are a group of developers who meet monthly to learn about anything and everything in the wide world of javascript. Whether you're hacking the backend in node, are using the latest and greatest front-end technologies, or are just getting started, Burlington Javascript is for you!

Our typical meetup generally runs for an hour with 45 minutes of planned content plus some time for discussion before and after the talk. Each talk is unique and might cater to a different audience, so if you see something that is either too basic or too advanced, keep your eyes peeled for something different next month.

We also hold community-led workshops every 4-6 months to help beginners and novices level-up, so if you don't know where to start, that's be the place!

We hope to see you soon!

**Comment by jhoguet** [comment]
Awesome thanks!

updated https://burlingtoncode.org/meetups/burlington-js/
