### ISSUE TITLE
January's meetup

### ISSUE THREAD

**Issue by jhoguet** [burlingtonjs/burlingtonjs#3]
- [x] Lock in Speaker (Jon Hoguet)
- [x] Lock in date with speaker
- [x] Lock in date with Venue
- [x] create meetup
- [x] market meetup (eg twitter) 
- [x] see if speaker will sponsor
- [x] Order Pizza
- [x] Get reimbursed if necessary

**Comment by donnie-coleman** [comment]
Are you not gonna be the speaker, Jon?

**Comment by jhoguet** [comment]
I am - I am trying to lock in the date with the Wordpress group because we were trying to do it the same night. I'll post it soon (by end of week).

**Comment by jhoguet** [comment]
Jan 13th... Josh for the Wordpress group still has Daft Labs on his meetup http://www.meetup.com/Burlington-WordPress-Meetup/events/226088108/ going to confirm he is going to use MSL

**Comment by jhoguet** [comment]
need to book with MSL, I'll try and do that tomorrow unless someone beats me to it

**Comment by donnie-coleman** [comment]
Is there anything about this particular Meetup that I need to announce on Twitter in addition to the standard message?

**Comment by jhoguet** [comment]
I just booked Jan 13th with MSL

@donnietron I'll probably have a more polished description once we get closer to the event

**Comment by jhoguet** [comment]
I didn't end up expensing the pizza - I had a lot going on, lost the receipt, got locked out of the expensing system, and it just wasn't a top priority. I did get reimbursed for the venue though.
