### ISSUE TITLE
February's Meetup

### ISSUE THREAD

**Issue by jhoguet** [burlingtonjs/burlingtonjs#4]
- [x] Lock in Speaker 
- [x] Lock in date with speaker
- [x] Lock in date with Venue
- [x] create meetup
- [x] market meetup (eg twitter) 
- [x] see if speaker will sponsor
- [ ] Order Pizza
- [x] Investigate Dominoes non-profit rumor
- [ ] Get reimbursed if necessary

**Comment by jhoguet** [comment]
@donnietron Burlington Code is still a WIP but here is the [doc](https://docs.google.com/document/d/1Tt_g3aa0Wn6vGD7tc7jXxhZDIbtMKzSw2o25NlC-ZXI/edit#heading=h.e0nj78bzrat4) we're using to track who is using MSL when. 

For now lets plan on Feb 3rd if that works for you guys. 

Do we have a speaker lined up?

cc @mattparrilla

**Comment by donnie-coleman** [comment]
yeah, Nick says he's in. We just need to pick a date and he'll work around
it, he said. I'll confirm that the 3rd works for him.

**Comment by donnie-coleman** [comment]
Nick says February 3rd at 6 works for him: we have our speaker lined up.

**Comment by jhoguet** [comment]
:+1:

**Comment by jhoguet** [comment]
@donnietron  Python group wants us to switch to 7. Nick said that would be ok

**Comment by donnie-coleman** [comment]
Ack

**Comment by jhoguet** [comment]
I will be meeting with Maria Thursday so I should be able to lock in all the dates for the rest of feb and march then. There is a small risk that by the time I book the date it won't be available but I think the risk is small.

**Comment by jhoguet** [comment]
we  have jet brains licenses we can give away, one from Jan and one from Feb see [here](https://docs.google.com/document/d/1jxk6D5SLwkhEkwiJMBpFR58h9dbbqlLG5QXvRaNg_aE/edit#heading=h.5m9x42edbwew) for the keys and there is alink to instructions further up that doc. 

Process from our end is 
1. capture their email at the event
2. write down the email in the doc linked above (mostly so we know we gave that one away)
3. email the member with the serial number and a link to the instructions

**Comment by jhoguet** [comment]
@mattparrilla @donnietron how did it go? Sorry I couldn't make it, but 80 degrees in FL was more compelling :)

Did DDC (Matt) end up covering the pizza?

**Comment by jhoguet** [comment]
just saw it was cancelled - any discussion of rescheduling it?

**Comment by donnie-coleman** [comment]
No BUT maybe we can do both in March that Monday? I'll float the idea to Nick
