### ISSUE TITLE
March's Meetup

### ISSUE THREAD

**Issue by jhoguet** [burlingtonjs/burlingtonjs#5]
- [x] Lock in Speaker (Ian)
- [x] Lock in date with speaker (March 7 6:00)
- [x] Lock in date with Venue
- [x] create meetup
- [ ] market meetup (eg twitter) 
- [ ] see if speaker will sponsor
- [ ] Order Pizza
- [ ] Get reimbursed if necessary

**Comment by mattparrilla** [comment]
Is my only role at this point to order pizza?

Note: I'm not complaining, I just want to make sure I'm not derelict in my duties.

**Comment by jhoguet** [comment]
I am streamlining the venue... so that part is taken care of.

I thought you were also trying to find sponsorship to pay for the venue. 

That is still something I could use help with, especially as we are now looking for $1200 / quarter instead of the $450 / quarter we need just for Burlington JS.

**Comment by jhoguet** [comment]
I still need $100 for the venue but otherwise this is all set. 

Side note: we had lower attendance than normal... thinking Monday might not be a good day.. we should favor Wednesday more aggressively. 

Also, Skinny Pancake closes early on Monday so if we go til 9 Skinny is not an option.
