### ISSUE TITLE
April's Meetup

### ISSUE THREAD

**Issue by jhoguet** [burlingtonjs/burlingtonjs#6]
- [x] Lock in Speaker (Matt P)
- [x] Lock in date with speaker 
- [x] Lock in date with Venue
- [x] create meetup
- [x] market meetup (eg twitter) 
- [x] see if speaker will sponsor
- [ ] Order Pizza
- [ ] Get reimbursed if necessary
- [ ] confirm with John Need (title, description, time)
- [ ] create 2nd meetup
- [ ] assess if 2 in one night is a bad thing
- [x] who owns the first session
- [ ] who owns the second session

**Comment by jhoguet** [comment]
I am currently only locking out MSL for Q1... by end of February... we'll need to see if BTVIgnite has gotten us a better venue or not - if not then we'll want to book out MSL even further

**Comment by jhoguet** [comment]
From Matt 

# Beyond the Fat Arrow: Functional Programming in Javascript

An introduction to functional concepts with an emphasis on real world techniques that you can use in your code today.

Matt will provide a quick survey of functional concepts and discuss the perils of mutating state and how you can use immutable data structures to protect against unwanted side effects.

Ben will discuss first class and higher order functions in Javascript. We'll look at how currying can be used to facilitate function composition, as well as how to write functions that lend themselves to composition. Finally, we'll review how you can use combinators, or functions that combine other functions, to build complex functions using simpler ones as building blocks.

**Comment by jhoguet** [comment]
I pencilled us in for April 6th https://docs.google.com/document/d/1Tt_g3aa0Wn6vGD7tc7jXxhZDIbtMKzSw2o25NlC-ZXI/edit

next steps

@mattparrilla can you confirm the date

@donnietron can you get it posted

**Comment by mattparrilla** [comment]
date is locked, just checked off the box!

**Comment by donnie-coleman** [comment]
Hey guys, Meetup allows events to send out a question to those who RSVP.

*Should we ask about the format? *

"Are you happy with the format?"
and/or
"How would you like to see the format of the #BTVJS changed?"

Or should we use survey monkey?

**Comment by jhoguet** [comment]
Lets discuss further at our next meeting.

**Comment by jhoguet** [comment]
this might be our second double (with John Need)... so we should assess whether or not it works...

we also should identify someone to own each session, so all 3 of us does not feel like we have to attend both sessions

**Comment by jhoguet** [comment]
we emailed Ben for pizza, if he cannot do it then we'll plan on having DDC pay for the pizza since Matt is presenting

**Comment by jhoguet** [comment]
emailed john need to confirm if we wants to present in April - otherwise we're looking at June

**Comment by mattparrilla** [comment]
@donnietron I scheduled something for the Monday before the next meetup at the skinny pancake for us to discuss a survey.

**Comment by donnie-coleman** [comment]
I created the meetup but haven't sent it out yet. Should i wait until we hear back from John Need?

**Comment by mattparrilla** [comment]
@donnietron we sent it out when we met on Monday!

**Comment by mattparrilla** [comment]
I'm happy to own the first session, as I'll be presenting.

**Comment by donnie-coleman** [comment]
You didn't. It was still hidden until Tuesday. Either way it's out now. :-)
