### ISSUE TITLE
May's Meetup

### ISSUE THREAD

**Issue by jhoguet** [burlingtonjs/burlingtonjs#7]
- [x] Lock in topic 1 (community ramp up)
- [x] Lock in date with speaker 
- [x] Lock in date with Venue
- [x] create meetup
- [x] market meetup (eg twitter) 
- [x] coordinate room setup with MSL
- [x] Order Pizza

**Comment by jhoguet** [comment]
we might be due for a ramp up... 

also, the open spaces format the Agile User Group does would be nice to try... basically pass out index cards and people write down topics they would like to talk about. Then people vote. Then the top x cards form x groups that discuss those topics.

**Comment by mattparrilla** [comment]
I like the voting idea. Let's do it.

**Comment by jhoguet** [comment]
Jeremy Danyow might be willing to do a talk in May

**Comment by jhoguet** [comment]
Matt sent a follow up email to Jeremy, lets plan on doing Ramp up either way. 

We also should emphasize marketing for the ramp up...

**Comment by mattparrilla** [comment]
Mentors:
- Tristan Davies
- Ben Glassman
- Jeff Margolis
- Jacob Legenre
- Orson Bradford
