### ISSUE TITLE
July Meetup

### ISSUE THREAD

**Issue by mattparrilla** [burlingtonjs/burlingtonjs#9]
- [x] Lock in Speaker 
- [x] Lock in date with speaker 
- [x] Lock in date with Venue
- [x] create meetup
- [x] market meetup (eg twitter) 
- [x] see if speaker will sponsor
- [x] Order Pizza

**Comment by jhoguet** [comment]
@donnietron @mattparrilla now that we have Need lined up for June I should start working on July...

I heard something about an Aaron but I don't know who that is.... should I start pursuing him? Can someone put me in contact with him?

**Comment by jhoguet** [comment]
nvm - I just found the email that tells me his name... and asked on that thread (facepalm)
